title: "FAQQ: Frequently asked Quantum Questions"
email: self@jackalyst.com
description: >- # this means to ignore newlines until "baseurl:"
  Testing
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jackalyst
github_username:  jackalyst
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    rss: rss

collections:
  faq: 
    permalink: "/:path/"
    output: true
defaults:
  - scope: 
      path: ""
    values:
      layout: "default"
  - scope:
      path: _faq
    values:
      layout: faq
# Build settings
markdown: kramdown
kramdown:
  extensions: [footnotes] 
local_theme: qrl
plugins:
  - jekyll-feed
